### ISSUE TITLE
关于代码验证的小问题

### ISSUE THREAD

**Issue by wjh-scut** [xyl-507/TGFAT#1]
您好，非常感谢您出色的工作。我在测试您代码的过程中，遇到了几个小问题，希望得到您的帮助：
1.关于Quick Start
![image](https://github.com/user-attachments/assets/63449641-a3ec-4e6c-bcbf-bc7150bb61d0)
这些位置的参数是不是该换成您这篇文章中的TGFAT算法啊？
2.关于测试数据集的json文件，我发现pysot并没有提供诸如UAVDT，DTB70等数据集的json文件。所有我想请问您，如果想在新数据集上测试，如何生成对应的json文件啊？

**Comment by xyl-507** [comment]
感谢您的关注。
1.哈哈哈，不好意思，这是在我之前的工作上改了一下readme，所以残留了一些痕迹。已修改
2.测试pysot没有的数据集时，可以参考SiamAPN的工作。https://github.com/vision4robotics/SiamAPN/issues/4#issuecomment-903086435

**Comment by wjh-scut** [comment]
非常感谢您的回复，关于UAV20L数据集我还有个问题想请教您：
我下载了UAV123数据集，发现它的data_seq文件夹中只有UAV123数据集，没有UAV20L。那么是不是需要我自己根据anno文件夹中UAV20L包含的文档名字，从UAV123数据集中手动将UAV20L的数据挑选出来组成UAV20L数据集啊？

**Comment by xyl-507** [comment]
不需要的






| |
yuanliangxue
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月28日 11:46 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [xyl-507/TGFAT] 关于代码验证的小问题 (Issue #1) |

非常感谢您的回复，关于UAV20L数据集我还有个问题想请教您：
我下载了UAV123数据集，发现它的data_seq文件夹中只有UAV123数据集，没有UAV20L。那么是不是需要我自己根据anno文件夹中UAV20L包含的文档名字，从UAV123数据集中手动将UAV20L的数据挑选出来组成UAV20L数据集啊？

**Comment by xyl-507** [comment]
需要的。可以创建软连接，不占内存

**Comment by wjh-scut** [comment]
谢谢，我在运行demo时，报了以下错误：
Traceback (most recent call last):
  File "tools/demo.py", line 15, in <module>
    from siamban.models.model_builder import ModelBuilder
  File "F:\Code\Vision_Track\tgfat\siamban\models\model_builder.py", line 15, in <module>
    from siamban.models.head import get_ban_head
  File "F:\Code\Vision_Track\tgfat\siamban\models\head\__init__.py", line 6, in <module>
    from siamban.models.head.ban import UPChannelBAN, DepthwiseBAN, MultiBAN
  File "F:\Code\Vision_Track\tgfat\siamban\models\head\ban.py", line 10, in <module>
    from siamban.core.xcorr import xcorr_fast, xcorr_depthwise, pixel_xcorr, tensor_to_pil, pixelwise_xcorr_1, pixelwise_xcorr_2, pg_xcorr
ImportError: cannot import name 'pixel_xcorr' from 'siamban.core.xcorr' (F:\Code\Vision_Track\tgfat\siamban\core\xcorr.py)
我看了下siamban.core.xcorr文件，发现里面只有xcorr_slow,xcorr_fast, xcorr_depthwise这三个函数,并没有需要导入的其他几个函数，请问这个该如何解决啊？

**Comment by xyl-507** [comment]
其他的互相关是我在实验过程中使用的，已经用不到了，我之后会更新一下代码。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月28日 18:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xyl-507/TGFAT] 关于代码验证的小问题 (Issue #1) |

谢谢，我在运行demo时，报了以下错误：
Traceback (most recent call last): File "tools/demo.py", line 15, in <module> from siamban.models.model_builder import ModelBuilder File "F:\Code\Vision_Track\tgfat\siamban\models\model_builder.py", line 15, in <module> from siamban.models.head import get_ban_head File "F:\Code\Vision_Track\tgfat\siamban\models\head\__init__.py", line 6, in <module> from siamban.models.head.ban import UPChannelBAN, DepthwiseBAN, MultiBAN File "F:\Code\Vision_Track\tgfat\siamban\models\head\ban.py", line 10, in <module> from siamban.core.xcorr import xcorr_fast, xcorr_depthwise, pixel_xcorr, tensor_to_pil, pixelwise_xcorr_1, pixelwise_xcorr_2, pg_xcorr ImportError: cannot import name 'pixel_xcorr' from 'siamban.core.xcorr' (F:\Code\Vision_Track\tgfat\siamban\core\xcorr.py)
我看了下siamban.core.xcorr文件，发现里面只有xcorr_slow,xcorr_fast, xcorr_depthwise这三个函数,并没有需要导入的其他几个函数，请问这个该如何解决啊？

**Comment by wjh-scut** [comment]
嗯嗯，谢谢
